### ISSUE TITLE
Build failure on older system with undeclare macro error

### ISSUE THREAD

**Issue by lgbaldoni** [snyball/Hawck#50] opened 2021-01-23 13:05 UTC
Trying to package Hawck for openSUSE, but unfortunately it builds correctly only for Tumbleweed (the rolling release).

Every version of Leap (the stable release) fails even with gcc10. I couldn't pinpoint the problem, here's the [full build log](https://github.com/snyball/Hawck/files/5860226/hawck-leap153.txt).

**Comment by snyball** [comment] 2021-01-23 13:13
Looks like invisible spaces, I'm guessing they were introduced when I copied and pasted that long list. You can confirm it with a `hexdump -C`, the most recent versions of gcc probably just treat them like normal ASCII spaces.

filter_ghosts.py:

```python
import sys

for c in sys.stdin.read():
    if ord(c) not in INVISIBLE_SPACES:
        sys.stdout.write(c)
```

**Comment by snyball** [comment] 2021-01-23 13:19
@lgbaldoni If the issue is caused by invisible spaces then you can send a pull request after running the filter and I'll get it merged.

**Comment by lgbaldoni** [comment] 2021-01-23 20:02
Looks like the problem is with the kernel version (5.3 vs. 5.10). I diffed `/usr/include/linux/input-event-codes.h` and the missing macros are all in there 😕

Do you see a way out of this?

**Comment by snyball** [comment] 2021-01-24 07:07
@lgbaldoni I think we need some `#ifdef`s, can you post the diff?

Then, for each of the missing macros we'll just have:

```c
#ifdef MAYBE_DECLARED
MAYBE_DECLARED,
#endif
```

Alternatively, one big (or several) `#if KERNEL_VERSION > x`

**Comment by snyball** [comment] 2021-01-24 07:10
The laziest option is to have an `#ifdef` for each of the macros, but that's a bad idea because it'll fail silently.

Thinking about it some more, checking the kernel version is probably best.

**Comment by lgbaldoni** [comment] 2021-01-24 08:56
I downloaded the various versions for each main release from upstream and compared them, in case you want to use the exact kernel version that introduced each key. Otherwise just look at the main one (53_510.diff).

[input_event_codes_diffs.tar.gz](https://github.com/snyball/Hawck/files/5861838/input_event_codes_diffs.tar.gz)

**Closed** 2021-01-24 16:35 UTC

**Comment by snyball** [comment] 2021-01-24 16:37
@lgbaldoni Added some `#if`s, let me know if that resolves the build problem. Thanks for the diffs.

**Comment by lgbaldoni** [comment] 2021-01-24 17:17
Works for me, thanks.
